title: iamdbc
name:  iamdbc
email: iamdbc@126.com
description: Hi, this is DBC.
keywords:  iamdbc
baseurl: ""
url: "http://iamdbc.github.io"
twitter_username: iamdbc
github_username:  iamdbc

markdown: kramdown

timezone: Asia/Shanghai
